# Generated by Django 2.2.16 on 2023-04-12 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230411_2251'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopingcart',
            name='ingredients',
        ),
        migrations.CreateModel(
            name='ShopingCartIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
                ('shoping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='payments.ShopingCart')),
            ],
        ),
    ]
