# Generated by Django 2.2.16 on 2023-04-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20230412_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopingcartingredient',
            name='shoping_cart',
        ),
        migrations.AddField(
            model_name='shopingcart',
            name='ingredients',
            field=models.ManyToManyField(to='payments.ShopingCartIngredient'),
        ),
    ]
