# Generated by Django 2.2.16 on 2023-04-12 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20230412_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopingcart',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='shopingcartingredient',
            name='shoping_cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='payments.ShopingCart'),
            preserve_default=False,
        ),
    ]
