# Generated by Django 2.2.16 on 2023-04-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230411_2251'),
        ('payments', '0004_auto_20230412_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingcart',
            name='amount_ingredients',
            field=models.ManyToManyField(to='recipes.AmountIngredient'),
        ),
        migrations.DeleteModel(
            name='ShopingCartIngredient',
        ),
    ]
