# Generated by Django 2.2.16 on 2023-04-14 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230413_2039'),
        ('payments', '0005_auto_20230412_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopingcart',
            name='amount_ingredients',
        ),
        migrations.AddField(
            model_name='shopingcart',
            name='recipes',
            field=models.ManyToManyField(related_name='shoping_cart', to='recipes.Recipe'),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
