# Generated by Django 2.2.16 on 2023-04-15 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230413_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountingredient',
            name='amount',
            field=models.FloatField(default=0, error_messages={'errors': 'Количество ингредиента не может быть отрицательным!'}, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.SmallIntegerField(default=1, error_messages={'errors': 'Время готовки не может быть менее одной минуты!'}, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='amountingredient',
            constraint=models.CheckConstraint(check=models.Q(amount__gte=0), name='min_value_amount'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(check=models.Q(cooking_time__gte=1), name='min_value_cooking_time'),
        ),
    ]
