# Generated by Django 2.2.16 on 2023-04-15 04:15

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230408_0433'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, follower=django.db.models.expressions.F('following')), name='cant_follow_yourself'),
        ),
    ]
